name: Test build

# Controls when the action will run.
on:
  # Triggers the workflow on push request on the main branch for changes in the specified paths.
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout
        uses: actions/checkout@main

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NodeJS dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Test Build
        run: npm run build
